### ISSUE TITLE
Objects with the same start time have unspecified ordering

### ISSUE THREAD

**Issue by tdresser** [w3c/performance-timeline#99] opened 2018-01-30 19:25 UTC
As per 4.2, 
> Objects with the same start time have unspecified ordering

This feels like an ergonomics footgun. I don't think the ordering here matters, but it would be nice to be consistent.

There's no obvious ordering though. You could sort by:
* start time
* entryType
* name
* duration

But sometimes this won't be unique. At some point, we should dig into what browsers do today, and see if we can find a way to make this consistent.

**Comment by igrigorik** [comment] 2018-01-31 07:30
Previous discussion: https://github.com/w3c/performance-timeline/issues/67

**Comment by toddreifsteck** [comment] 2018-02-22 19:26
Per discussion on 2/22, resolving Closing as By Design. If a use-case arises that needs this, lets bring it back.

**Closed by toddreifsteck** 2018-02-22 19:26 UTC
